### ISSUE TITLE
Sentiment score plot function

### ISSUE THREAD

**Issue by tanmayag97** [UBC-MDS/py-sentimentanalyzer#29]
Function 

- accepts the dataframe and column name provided: assert dataframe type,  assert column name is string type

- calls the helper function to get the updated frame with the column with the compound score: 

- Created the histogram plot: assert the type of the plot object

- Optionally add some summary text and return it as a string.

- Write unit test and check with pytest

**Comment by ranjitprakash1986** [comment]
Hi do we want to save the plots as a separate file or return it as an object for the user? What are your thoughts please put them here below @tanmayag97 @erictsai1208 @zchen156

**Comment by erictsai1208** [comment]
I'd say just return the plots. I don't think the function should do more than 1 thing.
