### ISSUE TITLE
Function 4

### ISSUE THREAD

**Issue by ranjitprakash1986** [UBC-MDS/py-sentimentanalyzer#8]
Create a bar chart of most common words used their frequencies and their sentiments

**Comment by erictsai1208** [comment]
I think maybe we can make it so that the bar chart plots the most positive and negative words? I feel like the wordcloud already creates a visualization for the common words.

**Comment by ranjitprakash1986** [comment]
> I think maybe we can make it so that the bar chart plots the most positive and negative words? I feel like the wordcloud already creates a visualization for the common words.

Sure that makes sense, we will use this function for only the top positive and negative words

**Comment by ranjitprakash1986** [comment]
Working on writing the docstring and how it connects with the overall package pipeline
